### ISSUE TITLE
Improve webpack 5 compatibility

### ISSUE THREAD

**Issue by bebraw** [shellscape/webpack-nano#20]
### Feature Use Case

It looks like webpack 5 `watch` usage has changed. When watch mode is enabled, then webpack expects a callback to be set.

I set up a minimal demo at https://github.com/bebraw/wps-watch-demo . If you run `npm start` after `npm install`, you should see the following:

```
 $ npm start

> wp5-demo@0.0.0 start /Users/juhovepsalainen/Projects/github/wps-watch-demo
> node --trace-deprecation node_modules/.bin/wp --mode development

⬡ webpack: Watching Files
(node:60643) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
    at webpack (/Users/juhovepsalainen/Projects/github/wps-watch-demo/node_modules/webpack/lib/webpack.js:145:5)
    at f (/Users/juhovepsalainen/Projects/github/wps-watch-demo/node_modules/webpack/lib/index.js:35:15)
    at run (/Users/juhovepsalainen/Projects/github/wps-watch-demo/node_modules/webpack-nano/lib/compiler.js:16:20)
    at doeet (/Users/juhovepsalainen/Projects/github/wps-watch-demo/node_modules/webpack-nano/bin/wp.js:79:3)
⬡ wps: Server Listening on: http://[::]:8080

⬡ webpack: asset main.js 73.1 KiB [emitted] [compared for emit] (name: main)
  asset index.html 198 bytes [compared for emit]
  runtime modules 25.2 KiB 11 modules
  cacheable modules 25 KiB
    modules by path ./node_modules/webpack-plugin-serve/lib/client/ 23.7 KiB
      modules by path ./node_modules/webpack-plugin-serve/lib/client/*.js 8.02 KiB 4 modules
      modules by path ./node_modules/webpack-plugin-serve/lib/client/overlays/*.js 15.7 KiB
        ./node_modules/webpack-plugin-serve/lib/client/overlays/progress-minimal.js 2.38 KiB [built] [code generated]
        ./node_modules/webpack-plugin-serve/lib/client/overlays/progress.js 3.88 KiB [built] [code generated]
        ./node_modules/webpack-plugin-serve/lib/client/overlays/status.js 8.27 KiB [built] [code generated]
        ./node_modules/webpack-plugin-serve/lib/client/overlays/util.js 1.17 KiB [built] [code generated]
    modules by path ./src/*.js 217 bytes
      ./src/index.js 77 bytes [built] [code generated]
      ./src/component.js 140 bytes [built] [code generated]
    ./node_modules/webpack-plugin-serve/client.js 1.05 KiB [built] [code generated]
  0 (webpack 5.1.0) compiled successfully in 152 ms

⬡ webpack: ⁿᵃⁿᵒ Duplicate build detected (28144bc52857f5b168c6)
```

That `Duplicate build detected` is a weird one as well and I don't know why we have it yet. It looks like it's coming from **webpack-nano** itself.

### Feature Proposal

Likely the callback webpack 5 expects should be defined anyhow or it should be injected only if watch mode is enabled in the configuration whichever is easier.

**Comment by EvanPurkhiser** [comment]
I'm still getting the `DEP_WEBPACK_WATCH_WITHOUT_CALLBACK` error when using multiple compiler configurations (`export default [config1, config2]`)

**Comment by shellscape** [comment]
@EvanPurkhiser sounds like you should open a new issue with a fresh reproduction. With this being a super tiny project, we'd also welcome a pull request.
